<a href="https://colab.research.google.com/github/trevoromondi/artificialintelligence/blob/main/AI_ML_Group_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Importing the required libraries***

In [115]:
import pandas as pd 
import numpy as np

In [116]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from numpy.random import uniform

***The Dataset and its Normalization***

In [117]:
data={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
      'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [118]:
dataset=pd.DataFrame(data)

In [119]:
X=dataset.drop('Target',axis=1)
y=dataset['Target']

In [120]:
X_norm = Normalizer(norm='max').fit_transform(X)

In [121]:
y_norm = Normalizer(norm = 'max').fit_transform(np.reshape(array(y), (1,-1)))
y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

In [122]:
X_norm

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [123]:
y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

***Setting up the weights, forward propagation, backward propagation and training for the Neural Network***

In [126]:
class Network(object):
  def __init__(self):
     #size parameters
      self.input = 3
      self.output = 6
      self.hidden = 3

      self.weight_1 = np.random.randn(self.input, self.hidden) #weight values from input layer to hidden layer 
      self.weight_2 = np.random.randn(self.hidden, self.output) #weight values from hidden layer to output layer 

  def forward(self, X_norm):
      self.a = np.dot(X_norm, self.weight_1)
      self.a2 = self.sigmoid(self.a) #activation function
      self.a3 = np.dot(self.a2, self.weight_2)
      output_1 = self.sigmoid(self.a3)
      return output_1

  def sigmoid(self, b, derivative=False):
      if(derivative == True):
        return b * (1-b)
      return 1/(1 + np.exp(-b))

  def backward(self, X_norm, y_norm, output_1):
      self.error = y_norm - output_1 #error gotten from the output
      self.delta = self.error * self.sigmoid(output_1, derivative=True)

      self.a2_error = self.delta.dot(self.weight_2.T) #how much the weights of the hidden layer contribute to the overall output error
      self.a2_delta = self.a2_error * self.sigmoid(self.a2, derivative=True) #applying the sigmoid derivative to the hidden layer error

      #updating the weights
      self.weight_1 += X_norm.T.dot(self.a2_delta)
      self.weight_2 += self.a2.T.dot(self.delta)  

  def training(self, X_norm, y_norm):
      output_1 = self.forward(X_norm)
      self.backward(X_norm, y_norm, output_1) 

NN = Network()
c = str(np.mean(np.square(y_norm - NN.forward(X_norm))))
for i in range(100): #number of epochs(100)
  if (i % 100 == 0):
    print("Loss: " + c )
    NN.training(X_norm, y_norm)
  

  

Loss: 0.14422214729549665


***Final output after 100 Epochs***

In [125]:
print("Predicted Output: " + str(NN.forward(X_norm)))  

Predicted Output: [[0.24764402 0.27254225 0.67185944 0.60813529 0.7857641  0.33017594]
 [0.27422536 0.46808382 0.68103812 0.63363362 0.59964949 0.30831165]
 [0.25025669 0.49572502 0.63226623 0.54773933 0.53794968 0.30758651]
 [0.22844792 0.27975998 0.65378893 0.55997632 0.77059257 0.30532454]
 [0.2655367  0.30353241 0.70930249 0.64510685 0.79111286 0.28725588]
 [0.26380823 0.3347606  0.66822892 0.6193361  0.72300067 0.33912666]]
